baseURL: http://example.org/
languageCode: en-us
title: "Newbound AI – AI-Powered Learning Assistant for Universities"
theme: agnes-hugo-theme
params:
  authorName: Los angeles, Ann Arbor, Newbound AI
  content:
    ButtonCaption: "Request a Demo"
    ButtonSubCaption: "Contact: info@newbound.ai"
    ButtonURL: https://newbound.ai/
    LeadDescription: "We build AI-native tools that make student learning smarter and teaching more effective."
    LeadTitle: Reimagining University Learning with AI
  dateFormat: Jan 2, 2023

  FeatureSectionTitle: What We Do

  feature:
    - FeatureTitle: Smart Learning Assistant
      FeatureDescription: Instantly helps students find answers from course videos and PDFs to improve learning efficiency.
      FeatureImage: images/feature-1.png
    - FeatureTitle: Instructor Dashboard
      FeatureDescription: Gives instructors real-time insights into student engagement and learning bottlenecks for better teaching strategies.
      FeatureImage: images/feature-2.png
    - FeatureTitle: Canvas LMS Integration
      FeatureDescription: Fully integrated with the Canvas Learning Management System and compliant with the LTI 1.3 standard.
      FeatureImage: images/feature-3.png
    - FeatureTitle: Cortex Search + LLM
      FeatureDescription: Combines Snowflake, Cortex Search, and large language models to deliver a powerful search experience.
      FeatureImage: images/feature-4.png

  google_analytics_id: GA-
  
  social:
    FacebookURL: https://facebook.com/
    GoogleURL: http://google.com
    TwitterURL: https://twitter.com/
menu:
  main:
    - Name: Contact
      URL: '#'
      weight: 1
    - Name: About us
      URL: '#'
      weight: 2
    - Name: FAQ's
      URL: '#'
      weight: 3
    - Name: Support
      URL: '#'
      weight: 4
